src code/src/carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_done_view, payment_done

urlpatterns = [

    url(r'^$',cart_home,name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^process/$', checkout_done_view, name='process'), 
    url(r'^success/$', payment_done, name='success'), 
    url(r'^update/$', cart_update, name='update'),
]

src code/src/ecommerce/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView 
from accounts.views import login_page,register_page,guest_register_view
from .views import home_page,about_page,contact_page
from carts.views import cart_home
from addresses.views import checkout_address_create_view,checkout_success
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'), 
    url(r'^about/$', about_page,name='about'), 
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^login/$', login_page,name='login'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^checkout/address/create/$', checkout_address_create_view,name='checkout_address_create_view'),
    url(r'^register/$', register_page,name='register'),
    url(r'^products/',include("products.urls",namespace='products')),
    url(r'^search/',include("search.urls",namespace='search')),
    url(r'^cart/',include("carts.urls",namespace='cart')),
    url(r'^bootstrap/$',TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^resgister/guest/$', guest_register_view,name='guest_register_view'),    

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src code/src/products/urls.py
from django.conf.urls import url
from products.views import ProductListView,ProductDetailSlugView

urlpatterns = [

    url(r'^$',ProductListView.as_view(),name='list'),
    url(r'^(?P<slug>[\w-]+)/$',ProductDetailSlugView.as_view(),name='detail'),    
]

src code/src/templates/base.html
{% load static %}
<!doctype html>
    <html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Base Template</title>
    {% include 'base/css.html '  %} 
    {% block base_head %}
    {% endblock %}
  </head>
  <body>
    {% include 'base/navbar.html' with brand_name='eCommerce' %}  
  <div class="container">
     {% block content%}{% endblock %} 
    </div>
     {% include 'base/js.html'  %}  
  </body>
</html>

src code/src/templates/home_page.html
{% extends "base.html" %}
{% load static %}
{% block base_head%}
{% url 'products:list' as product_list_url %}

<link rel="stylesheet" href='{% static "css/main.css" %}'>
{% endblock %}

{% block content %}
<div class='text-center'>
  <!-- <h1>{{title}}</h1> -->
  </div>
  <!-- <div class="container"> -->
      <div class='row'>
          <div class="col" id="img1">
            <!-- <img src="{% static 'img/b.jpg'%}"  class='img-fluid' alt="" style="background-position: left;"> -->
          </div>
      </div>
      {% if requesr.user.is_authenticated %}
      <div class='row'>
        <div class="col">
          <h1>Premium</h1> 
            <!-- {{ premium_content }} -->
        </div>
    </div>
    {% endif %}
  <!-- </div> -->

  <section class="banner-image">
    <div class="container">
        <div class="banner-content">
            <h1 style="color: beige;">Find it, love it, buy it.</h1>
            <p style="color: beige;">Flat 40% OFF on all our premium brands</p>
            <a href="{% url 'products:list' %}" class="btn btn-danger btn-lg active" style="color: beige;">Shop Now</a>
        </div>
    </div>
  </section>

{% endblock%}
<!doctype html>
    <html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href='{% static "css/main.css" %}'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
  </head>
  <body >
 
  </body>
</html>