src code/src/carts/urls.py
from django.conf.urls import url
from .views import cart_home, cart_update, checkout_home, checkout_done_view, payment_done

urlpatterns = [

    url(r'^$',cart_home,name='home'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^process/$', checkout_done_view, name='process'), 
    url(r'^success/$', payment_done, name='success'), 
    url(r'^update/$', cart_update, name='update'),
]

src code/src/ecommerce/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView 
from accounts.views import login_page,register_page,guest_register_view
from .views import home_page,about_page,contact_page
from carts.views import cart_home
from addresses.views import checkout_address_create_view,checkout_success
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page,name='home'), 
    url(r'^about/$', about_page,name='about'), 
    url(r'^contact/$', contact_page,name='contact'),
    url(r'^login/$', login_page,name='login'),
    url(r'^logout/$', LogoutView.as_view(),name='logout'),
    url(r'^checkout/address/create/$', checkout_address_create_view,name='checkout_address_create_view'),
    url(r'^register/$', register_page,name='register'),
    url(r'^products/',include("products.urls",namespace='products')),
    url(r'^search/',include("search.urls",namespace='search')),
    url(r'^cart/',include("carts.urls",namespace='cart')),
    url(r'^bootstrap/$',TemplateView.as_view(template_name='bootstrap/example.html')),
    url(r'^resgister/guest/$', guest_register_view,name='guest_register_view'),    

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src code/src/carts/models.py
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save,m2m_changed


User=settings.AUTH_USER_MODEL
class CartManager(models.Manager):
    def new_or_get(self,request):
        cart_id=request.session.get("cart_id",None)
        qs=self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user=request.user
                cart_obj.save()
        else:
            cart_obj=Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return  cart_obj,new_obj
          
    def new(self,user=None):
        user_obj=None
        if user is not None:
            if user.is_authenticated():
                user_obj=user  
        return  self.model.objects.create(user=user_obj)
# Create your models here.
class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)
    
    objects=CartManager()
    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender,instance,action,*args,**kwargs):
    if action =='post_add' or action =='post_remove ' or action =='post_clear':
        products=instance.products.all()
        total=0
        for x in products:
            total +=x.price 
        instance.subtotal=total
        instance.save()

m2m_changed.connect(m2m_changed_cart_receiver,sender=Cart.products.through)

def pre_save_cart_receiver(sender,instance, *args,**kwargs):
    if instance.subtotal >0:
        instance.total=float(instance.subtotal)*1.08 
    else:
        instance.total=0.00

pre_save.connect(pre_save_cart_receiver,sender=Cart )

src code/src/carts/views.py
from django.shortcuts import render,redirect    
from products.models import Product
from .models import Cart
from orders.models import Order 
from billing.models import BillingProfile
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address

# Create your views here.
from accounts.forms import LoginForm,GuestForm

def cart_create(user=None):
    cart_obj,new_obj=Cart.objects.create(user=None)
    return cart_obj

def cart_home(request):
    cart_obj,new_obj=Cart.objects.new_or_get(request)
    return render(request,"carts/home.html",{"cart":cart_obj})    

def cart_update(request):
    product_id = request.POST.get('product_id')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
             cart_obj.products.remove(product_obj)
        else:
            cart_obj.products.add(product_obj)
        request.session['cart_items'] = cart_obj.products.count()
    return redirect('cart:home')

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")  
    
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }
    return render(request, "carts/checkout.html", context)
   
def checkout_done_view(request):
    return render(request, "carts/process.html", {})

def payment_done(request):
    return render(request,"carts/success.html",{})
    

src code/src/carts/templates/carts/checkout-done.html
  
{% extends "base.html" %}

{% block content %}
<div   >
    <h1>Thank you ordering </h1>
</div>
{% endblock %}

src code/src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}
{{ object.order_id }}--{{ object.cart }}
{% if not billing_profile %}
<div class="row text-center">
<div class="col-12 col-md-6">
    <p class="lead">Login</p>
    {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri  %}
</div>
<div class="col-12 col-md-6">
    Continue as Guest

    {% url "guest_register" as guest_register_url %}
    {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
</div>
</div>   
{% else %}
{%if not object.shipping_address %} 
<div class="row">
    <div class="col-md-6 mx-auto col-10">
        <p class="lead">Shipping Address</p>
        <hr/>
    {% url "checkout_address_create" as checkout_address_create %}
    {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}    </div> 
    </div> 
{% elif not object.billing_address %}
<div class="row">
<div class="col-md-6 mx-auto col-10">
    <p class="lead">Billing Address</p>
    <hr/>
{% url "checkout_address_create" as checkout_address_create %}
{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
</div> 
</div>
{% else  %}
<h1>Finalize Checkout</h1>
<p>Cart Total:{{ object.cart.total }}</p>
<p>Shipping Total:{{ object.shipping_total }}</p>
<p>Order Total:{{ object.total }}</p>

<form class='form' method='POST'action="">{% csrf_token %}
    <button class="btn btn success" type="submit">Checkout</button>
</form>
{% endif %}
{% endif %}
{% endblock %} 

src code/src/carts/templates/carts/detail.html
{% extends "base.html" %}

{% block content %}
<body>
    

<div class='container'>
    <div class='row'>
        <div class='col-12 col-md-6'>
    <h1>{{ object.title }}</h1>
    {{ object.timestamp|timesince}} ago
    {{ object.description|linebreaks }} <br>
    {% if object.image %}
        <img src="{{ object.image.url }}" class='img-fluid'  />
    {% endif %}
</div>
<div class='col-12 col-md-6'>
    {% include 'products/snippets/update-cart.html' with product=object cart=cart %}
    
</div>
</div>
</div>
</div>
</body>
{% endblock %}

src code/src/carts/templates/carts/home.html
  
{% extends "base.html" %}

{% block content %}
<h1>Cart</h1>
{% if cart.products.exists %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product Name</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
        {% for product in cart.products.all %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td> <a href="{{ product.get_absolute_url }}">{{ product.title  }}</a>
          {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
        </td>
        <td>{{ product.price  }}</td>
      </tr>
      {% endfor %}
      <tr>
        <th colspan="2"></th>
        <td><b>Subtotal</b> {{ cart.subtotal }}</td>
      </tr>
      <tr>
        <th colspan="2"></th>
        <td><b>Total</b> {{ cart.total }}</td>
      </tr>
      <tr>
        <th colspan="2"></th>
        <td><a class='btn btn-lg btn-success'href='{% url "cart:checkout" %}'>Checkout</a></td>
      </tr>
    
    </tbody>
  </table>

{% else %}
<p class="lead">Cart is empty</p>
{% endif %}
{% endblock %}

src code/src/carts/templates/carts/process.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid black;
  border-bottom: 16px solid black;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
</head>
<body>
    <br>
    <br>
<center>
<h2>Your Payment is processing</h2>
  <h3>Don't Press refresh or Back wait till the page get's redirected automatically...</h3>
<div class="loader"></div>
</center>
<script>
    setTimeout(function(){
        window.location.href = "{% url 'cart:success' %}";
    }, 3000);
</script>
</body>
</html>

src code/src/carts/templates/carts/success.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Order Confirmed</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
body {
	font-family: 'Varela Round', sans-serif;
}
.modal-confirm {		
	color: #636363;
	width: 325px;
	font-size: 14px;
}
.modal-confirm .modal-content {
	padding: 20px;
	border-radius: 5px;
	border: none;
}
.modal-confirm .modal-header {
	border-bottom: none;   
	position: relative;
}
.modal-confirm h4 {
	text-align: center;
	font-size: 26px;
	margin: 30px 0 -15px;
}
.modal-confirm .form-control, .modal-confirm .btn {
	min-height: 40px;
	border-radius: 3px; 
}
.modal-confirm .close {
	position: absolute;
	top: -5px;
	right: -5px;
}	
.modal-confirm .modal-footer {
	border: none;
	text-align: center;
	border-radius: 5px;
	font-size: 13px;
}	
.modal-confirm .icon-box {
	color: #fff;		
	position: absolute;
	margin: 0 auto;
	left: 0;
	right: 0;
	top: -70px;
	width: 95px;
	height: 95px;
	border-radius: 50%;
	z-index: 9;
	background: #82ce34;
	padding: 15px;
	text-align: center;
	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);
}
.modal-confirm .icon-box i {
	font-size: 58px;
	position: relative;
	top: 3px;
}
.modal-confirm.modal-dialog {
	margin-top: 80px;
}
.modal-confirm .btn {
	color: #fff;
	border-radius: 4px;
	background: #82ce34;
	text-decoration: none;
	transition: all 0.4s;
	line-height: normal;
	border: none;
}
.modal-confirm .btn:hover, .modal-confirm .btn:focus {
	background: #6fb32b;
	outline: none;
}
.trigger-btn {
	display: inline-block;
	margin: 100px auto;
}
</style>
</head>
<body>
<!-- <div class="text-center"> -->
	<!-- Button HTML (to Trigger Modal) -->
	<!-- <a href="#myModal" class="trigger-btn" data-toggle="modal">Click to Open Confirm Modal</a> -->
<!-- </div> -->

<!-- Modal HTML -->
<!-- <div id="myModal" class="modal fade"> -->
	<div class="modal-dialog modal-confirm">
		<div class="modal-content">
			<div class="modal-header">
				<div class="icon-box">
					<i class="material-icons">&#xE876;</i>
				</div>				
				<h4 class="modal-title w-100">Awesome!</h4>	
			</div>
			<div class="modal-body">
                <p class="text-center"><h5 style="line-height: 35px; text-align: center;">Your purchase has been confirmed. Thank You for your purchase Take 20% off on your next order with the coupon code:</h5><br><h3 style="text-align: center;">DATTEBAYO!</h3></p>
                <p></p>
			</div>
			<div class="modal-footer">
				<a href="{% url 'home' %}" class="btn btn-success btn-block"><button class="btn btn-success btn-block">OK</button></a>
			</div>
		</div>
	</div>
<!-- </div>      -->
</body>
</html>